#!/usr/bin/python


class Constants:
    WINDOW_NAME = "window"
    TAB_NAME = "tab"
    WIDGET_NAME = "widget"
    LINE_NAME = "line"

    CONFIGURABLE_TEXT_BOX_TYPE = "ConfigurableTextBox"
    DROP_DOWN_TEXT_BOX_TYPE = "DropDownTextBox"
    SIMPLE_DROP_DOWN_TYPE = "SimpleDropDown"
    SIMPLE_BUTTON_TYPE = "SimpleButton"
    VIDEO_WINDOW_TYPE = "video"
    COMPASS_TYPE = "compass"
    ATTITUDE_TYPE = "AttitudeWidget"
    FULL_FLIGHT_TYPE = "FullFlightDisplay"
    ANNUNCIATOR_TYPE = "AnnunciatorPanel"
    SIMPLE_CONSOLE_TYPE = "SimpleConsole"
    COMPLETE_CONSOLE_TYPE = "CompleteConsole"
    BROWSE_TYPE = "Browse"
    MULTI_GRAPH_TYPE = "MultiBarGraph"
    ROV_STATUS_TYPE = "ROVStatusWidget"
    MISSION_STATUS_TYPE = "MissionStatusWidget"
    STATUS_EVENT_TYPE = "StatusEventWidget"
    MAP_TYPE = "MapWidget"
    VIDEO_SWITCH_TYPE = "VideoSwitcherWidget"

    CONFIG_ATTRIBUTE = "config"
    TAB_ATTRIBUTE = "tab"
    LABEL_ATTRIBUTE = "label"
    VALUE_ATTRIBUTE = "value"
    TITLE_ATTRIBUTE = "title"
    TYPE_ATTRIBUTE = "type"
    FONT_ATTRIBUTE = "font"
    FONT_SIZE_ATTRIBUTE = "fontsize"
    X_POS_ATTRIBUTE = "x"
    Y_POS_ATTRIBUTE = "y"
    HIDDEN_ATTRIBUTE = "hidden"
    DRAGGABLE_ATTRIBUTE = "draggable"
    FOREGROUND_ATTRIBUTE = "foreground"
    BACKGROUND_ATTRIBUTE = "background"
    BORDER_WIDTH_ATTRIBUTE = "borderwidth"
    RELIEF_ATTRIBUTE = "relief"
    WIDTH_ATTRIBUTE = "width"
    HEIGHT_ATTRIBUTE = "height"
    SOURCE_ATTRIBUTE = "source"
    DIMENSIONS_ATTRIBUTE = "dimensions"
    FULLSCREEN_ATTRIBUTE = "fullscreen"
    LOCK_ASPECT_RATIO_ATTRIBUTE = "lockAspectRatio"
    SIZE_ATTRIBUTE = "size"
    THEME_ATTRIBUTE = "theme"
    URL_ATTRIBUTE = "url"
    ROW_NUMBER_ATTRIBUTE = "row_number"
    COLUMN_NUMBER_ATTRIBUTE = "column_number"
    TRANSPARENT_ATTRIBUTE = "transparent"
    MIN_ATTRIBUTE = "minimum"
    MAX_ATTRIBUTE = "maximum"
    COLOR_ATTRIBUTE = "color"
    SCALE_ATTRIBUTE = "scale"
    ENABLED_ATTRIBUTE = "enabled"

    # ATTRIBUTE
    BATTERY_VOLTAGE_VALUE = "batteryVoltage"
    V5_VOLTAGE_VALUE = "v5Voltage"
    V33_VOLTAGE_VALUE = "v33Voltage"
    CURRENT_VALUE = "current"

    def __init__(self):
        pass
